.TH "file" 3 "Mon Apr 6 2020" "Version 1.0.5" "pdlvlfile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file \- Functions that write unformatted binary data to file\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Functions that write unformatted binary data to file\&. 

This file contains functions to write to file:
.IP "\(bu" 2
Byte arrays
.IP "\(bu" 2
Single bytes
.IP "\(bu" 2
16 and 32 bit integers
.IP "  \(bu" 4
in little endian
.IP "  \(bu" 4
in big endian 
.PP

.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for pdlvlfile from the source code\&.
