.TH "LevelHeader" 3 "Mon Apr 6 2020" "Version 1.0.5" "pdlvlfile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LevelHeader
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBbgTop\fP [BGTOP_LENGTH]"
.br
.RI "Name of a file containing image data\&. Used for loading the bottom-layer background image\&. "
.ti -1c
.RI "char \fBtileset\fP [TILESET_LENGTH]"
.br
.RI "Name of a file containing image data\&. Used for loading the top-layer background image\&. "
.ti -1c
.RI "char \fBmusic\fP [MUSIC_LENGTH]"
.br
.RI "Name of a file containing image data\&. Used for loading the tileset\&. "
.ti -1c
.RI "uint16_t \fBnumdivs\fP"
.br
.RI "Name of a file containing audio data\&. Used for loading the background music\&. "
.in -1c
.SH "Detailed Description"
.PP 
A struct that defines a level header 

.SH "Author"
.PP 
Generated automatically by Doxygen for pdlvlfile from the source code\&.
