.TH "Tile" 3 "Mon Apr 6 2020" "Version 1.0.5" "pdlvlfile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tile
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBgfx\fP"
.br
.ti -1c
.RI "uint8_t \fBcode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct representing a tile\&. 
.SH "Field Documentation"
.PP 
.SS "uint8_t Tile::code"
Code index\&. 
.SS "uint8_t Tile::gfx"
Graphics index\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for pdlvlfile from the source code\&.
