.TH "todo" 3 "Mon Apr 6 2020" "Version 1.0.5" "pdlvlfile" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todoTodo List 
 \- 
.IP "\fBGlobal \fBpdlvl_readheader\fP (FILE *stream, \fBLevel\fP *lvl)\fP" 1c
Tell the user whether sub-divisions have been freed or not\&.  
.IP "\fBGlobal \fBpdlvl_readlevel\fP (FILE *stream, \fBLevel\fP *lvl)\fP" 1c
Check size of level structure and match it with the number of bytes read\&. 
.PP

